### ISSUE TITLE
using docker (boot2docker), converge on chef-server fails

### ISSUE THREAD

**Issue by ricardolupo** [stephenlauck/chef-services#14]
``````
           ================================================================================
           Error executing action `create` on resource 'hostsfile_entry[33.33.33.10]'
           ================================================================================

           Errno::EBUSY
           ------------
           file[/etc/hosts] (dynamically defined) had an error: Errno::EBUSY: Device or resource busy @ sys_fail2 - (/etc/.hosts20151104-364-1iletxz, /etc/hosts)

           Cookbook Trace:
           ---------------

           /tmp/kitchen/cache/cookbooks/hostsfile/providers/entry.rb:44:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/hostsfile/providers/entry.rb:44:in `block in class_from_file'

           Resource Declaration:
           ---------------------
       # In /tmp/kitchen/cache/cookbooks/test/recipes/hostsfile.rb


             2:   hostname  'chef.example.com'
             3:   unique    true
         4: end
             5:

           Compiled Resource:
           ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/test/recipes/hostsfile.rb:1:in `from_file'

           hostsfile_entry("33.33.33.10") do
             action [:create]
         retries 0
         retry_delay 2
         default_guard_interpreter :default
             declared_type :hostsfile_entry
             cookbook_name "test"

         hostname "chef.example.com"
             unique true
         ip_address "33.33.33.10"
       end


       Running handlers:
       [2015-11-04T23:22:22+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-11-04T23:22:22+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 02 seconds
       [2015-11-04T23:22:22+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-11-04T23:22:22+00:00] ERROR: hostsfile_entry[33.33.33.10] (test::hostsfile line 1) had an error: Errno::EBUSY: file[/etc/hosts] (dynamically defined) had an error: Errno::EBUSY: Device or resource busy @ sys_fail2 - (/etc/.hosts20151104-364-1iletxz, /etc/hosts)
       [2015-11-04T23:22:24+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <chef-server-centos-67>.
>>>>>> Please see .kitchen/logs/chef-server-centos-67.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 9010
']
>>>>>> ----------------------
zlib(finalizer): the stream was freed prematurely.```
``````

**Comment by stephenlauck** [comment]
Docker support will not let us change the /etc/hosts of the containers as far as I know.
